# ─── Ollama — local embedding model server (required by Letta for agent creation) ───
if $LETTA_SKIP || $OLLAMA_SKIP; then
  ok "Ollama (skipped)"
else
  if command -v ollama &>/dev/null; then
    ok "ollama already installed: $(ollama --version 2>/dev/null | head -1 || echo installed)"
  else
    echo "  Installing Ollama..."
    if curl -fsSL https://ollama.com/install.sh | sh >> "$LOG_FILE" 2>&1; then
      ok "ollama installed"
    else
      warn "ollama install failed — Letta will need OpenAI embeddings (set OPENAI_API_KEY)"
      OLLAMA_SKIP=true
    fi
  fi

  if ! $OLLAMA_SKIP && command -v ollama &>/dev/null; then
    # Ollama installer creates /etc/systemd/system/ollama.service (system-level)
    # Bind to 0.0.0.0 so Docker bridge containers can reach it via host.docker.internal
    sudo mkdir -p /etc/systemd/system/ollama.service.d
    printf '[Service]\nEnvironment="OLLAMA_HOST=0.0.0.0:11434"\n' \
      | sudo tee /etc/systemd/system/ollama.service.d/override.conf > /dev/null
    sudo systemctl daemon-reload 2>/dev/null || true
    sudo systemctl enable ollama 2>/dev/null || true
    sudo systemctl start ollama 2>/dev/null || true
    # Wait for Ollama to be ready (up to 30s)
    for _oi in $(seq 1 15); do
      ollama list &>/dev/null 2>&1 && break
      sleep 2
    done
    if ! ollama list &>/dev/null 2>&1; then
      warn "ollama service not responding — check: sudo systemctl status ollama"
      OLLAMA_SKIP=true
    fi
  fi

  if ! $OLLAMA_SKIP && command -v ollama &>/dev/null; then
    if ollama list 2>/dev/null | grep -q "nomic-embed-text"; then
      ok "nomic-embed-text (exists)"
    else
      echo -n "  Pulling nomic-embed-text (~274MB)..."
      if ollama pull nomic-embed-text >> "$LOG_FILE" 2>&1; then
        echo -e " ${GREEN}✓${NC}"
      else
        echo -e " ${YELLOW}⚠ pull failed — retry: ollama pull nomic-embed-text${NC}"
        OLLAMA_SKIP=true
      fi
    fi
  fi
fi

# ─── Letta password + credentials (generated before Docker container setup) ───
if ! $LETTA_SKIP; then
  if [[ -z "$LETTA_PASSWORD" ]]; then
    LETTA_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  fi
  mkdir -p "$HOME/.config/letta"
  cat > "$HOME/.config/letta/credentials" << CREDEOF
# Letta server credentials (generated by titan-setup ${SCRIPT_VERSION})
LETTA_SERVER_PASSWORD=${LETTA_PASSWORD}
LETTA_BASE_URL=http://127.0.0.1:${LETTA_PORT}
LETTA_API_KEY=${LETTA_PASSWORD}
CREDEOF
  chmod 600 "$HOME/.config/letta/credentials"

  # Docker env file for Letta container
  cat > "$HOME/.config/letta/docker.env" << ENVEOF
SECURE=true
LETTA_SERVER_PASSWORD=${LETTA_PASSWORD}
ENVEOF
  if ! $OLLAMA_SKIP && command -v ollama &>/dev/null; then
    echo "OLLAMA_BASE_URL=http://host.docker.internal:11434/v1" >> "$HOME/.config/letta/docker.env"
  fi
  if ! $CCFLARE_SKIP && command -v better-ccflare &>/dev/null; then
    echo "ANTHROPIC_BASE_URL=http://host.docker.internal:${CCFLARE_PROXY_PORT}" >> "$HOME/.config/letta/docker.env"
    echo "ANTHROPIC_API_KEY=sk-proxy-via-ccflare" >> "$HOME/.config/letta/docker.env"
  elif [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "$HOME/.config/letta/docker.env"
  fi
  chmod 600 "$HOME/.config/letta/docker.env"
  ok "Letta credentials (~/.config/letta/)"
fi

# ─── Letta Server — persistent memory backend for claude-subconscious ───
if $LETTA_SKIP; then
  ok "Letta server (skipped)"
elif ! command -v docker &>/dev/null; then
  warn "Letta server skipped — Docker not available (install Docker and re-run)"
  LETTA_SKIP=true
else
  # Pull Letta Docker image (bundles Postgres+pgvector)
  _DOCKER_BIN=$(command -v docker)
  if run_q docker pull letta/letta:latest; then
    ok "letta/letta:latest image"
  else
    warn "letta docker pull failed — check: docker pull letta/letta:latest"
    LETTA_SKIP=true
  fi

  if ! $LETTA_SKIP; then
    mkdir -p "$HOME/.letta/.persist/pgdata"

    # Systemd user service using --env-file to avoid secrets in unit file
    mkdir -p "$HOME/.config/systemd/user"
    cat > "$HOME/.config/systemd/user/letta.service" << SERVICEEOF
[Unit]
Description=Letta persistent memory server
After=default.target

[Service]
Type=simple
ExecStartPre=-${_DOCKER_BIN} rm -f letta-server
ExecStart=${_DOCKER_BIN} run --rm --name letta-server -p 127.0.0.1:${LETTA_PORT}:8283 --add-host=host.docker.internal:host-gateway -v %h/.letta/.persist/pgdata:/var/lib/postgresql/data --env-file %h/.config/letta/docker.env letta/letta:latest
ExecStop=${_DOCKER_BIN} stop letta-server
Restart=on-failure
RestartSec=15

[Install]
WantedBy=default.target
SERVICEEOF

    systemctl --user daemon-reload 2>/dev/null || true
    systemctl --user enable letta 2>/dev/null || true
    systemctl --user start letta 2>/dev/null || true
    ok "letta service (http://127.0.0.1:${LETTA_PORT})"

    # Wait for Letta health (up to 60s — Postgres init slow on first run)
    _LETTA_READY=false
    for _li in $(seq 1 30); do
      if curl -sf "http://127.0.0.1:${LETTA_PORT}/v1/health" &>/dev/null; then
        _LETTA_READY=true
        break
      fi
      sleep 2
    done
    if $_LETTA_READY; then
      ok "letta server healthy (http://127.0.0.1:${LETTA_PORT})"
    else
      warn "letta server not responding yet — check: journalctl --user -u letta -f"
      echo "  (Postgres init can take 30-60s on first run; service will recover automatically)"
    fi
  fi
fi

# ─── better-ccflare — Claude Code load balancer proxy ───
# Distributes requests across Claude OAuth, Vertex AI, Z.ai, OpenRouter, local models
# Dashboard: http://${CCFLARE_HOST}:${CCFLARE_PORT} | Docs: https://github.com/tombii/better-ccflare

if $CCFLARE_SKIP; then
  ok "better-ccflare (skipped — use --ccflare-* flags to configure)"
else
  # Phase A: Install from source with patches
  # Upstream bugs: NULL constraint on refresh_token for kilo/zai/minimax/console CLI modes
  # See: https://github.com/tombii/better-ccflare/issues/83
  if ! command -v better-ccflare &>/dev/null; then
    _BCF_SRC=$(mktemp -d -t bcf-src-XXXXXX)
    _CLEANUP_DIRS+=("$_BCF_SRC")
    if run_q git clone --depth=1 https://github.com/tombii/better-ccflare.git "$_BCF_SRC"; then
      # Patch: fix NULL constraint for refresh_token in CLI account creation
      python3 - "$_BCF_SRC/packages/cli-commands/src/commands/account.ts" << 'PYEOF'
import sys, pathlib
f = pathlib.Path(sys.argv[1])
c = f.read_text()
for provider, values_placeholder, array_signature in [
    ("claude-console-api", "NULL, NULL, NULL, ?, 0, 0", "validatedApiKey,\n\t\t\tnow,\n\t\t\tvalidatedPriority,\n\t\t\tcustomEndpoint"),
    ("minimax",            "NULL, NULL, NULL, ?, 0, 0", "validatedApiKey,\n\t\t\tnow,\n\t\t\tvalidatedPriority,\n\t\t\tnull"),
    ("zai",                "NULL, NULL, NULL, ?, ?, ?", "validatedApiKey,\n\t\t\tnow,\n\t\t\t0,"),
    ("kilo",               "?, ?, ?, ?, ?, ?, ?",       None),  # separate pattern
]:
    if provider == "kilo":
        old = '"kilo",\n\t\t\tvalidatedApiKey,\n\t\t\tnull,'
        new = '"kilo",\n\t\t\tvalidatedApiKey,\n\t\t\tvalidatedApiKey,'
    else:
        old = f'"{provider}",\n\t\t\tvalidatedApiKey,\n\t\t\tnow,'
        new = f'"{provider}",\n\t\t\tvalidatedApiKey,\n\t\t\tvalidatedApiKey,\n\t\t\tnow,'
    c = c.replace(old, new)
f.write_text(c)
PYEOF
      # Also fix SQL placeholders: NULL, NULL, NULL → ?, NULL, NULL for console/minimax/zai
      python3 - "$_BCF_SRC/packages/cli-commands/src/commands/account.ts" << 'PYEOF'
import sys, pathlib
f = pathlib.Path(sys.argv[1])
c = f.read_text()
# Replace the SQL NULL,NULL,NULL with ?,NULL,NULL for API-key providers that store key as refresh_token
# Only target the INSERT patterns that still have the old SQL (not already patched)
c = c.replace(
    ") VALUES (?, ?, ?, ?, NULL, NULL, NULL,",
    ") VALUES (?, ?, ?, ?, ?, NULL, NULL,"
)
f.write_text(c)
PYEOF
      mkdir -p "$HOME/.bun/bin"
      # NOTE: cd is required — `bun --cwd` does not propagate CWD to shell subprocesses
      # in the build script, which uses relative paths like ../../packages/
      if run_q bun install --cwd "$_BCF_SRC" && (cd "$_BCF_SRC/apps/cli" && run_q bun run build); then
        _BCF_DIST="$_BCF_SRC/apps/cli/dist/better-ccflare"
        if [[ -f "$_BCF_DIST" ]]; then
          mkdir -p "$HOME/.bun/bin" "$HOME/.local/bin"
          install -m 0755 "$_BCF_DIST" "$HOME/.bun/bin/better-ccflare"
          install -m 0755 "$_BCF_DIST" "$HOME/.local/bin/better-ccflare"
          ok "better-ccflare (built from source + NULL constraint patches applied)"
        else
          warn "better-ccflare build succeeded but binary not found at $_BCF_DIST"
          if [[ "$ARCH_GO" == "arm64" ]]; then
            warn "  arm64: no pre-built npm binary available — skipping"
          else
            run_q bun install -g better-ccflare || warn "better-ccflare npm install also failed"
          fi
        fi
      else
        warn "better-ccflare build failed"
        if [[ "$ARCH_GO" == "arm64" ]]; then
          warn "  arm64: npm fallback binary is x86-64 only — skipping"
          warn "  Fix: bun install --cwd <bcf-src> && bun --cwd <bcf-src>/apps/cli run build"
        else
          run_q bun install -g better-ccflare || warn "better-ccflare npm install also failed"
        fi
      fi
    else
      warn "better-ccflare repo clone failed"
      if [[ "$ARCH_GO" == "arm64" ]]; then
        warn "  arm64: npm fallback binary is x86-64 only — must build from source"
      else
        run_q bun install -g better-ccflare || warn "better-ccflare install failed"
      fi
    fi
  else
    ok "better-ccflare (exists)"
  fi

  # Phase B: Systemd user service
  # Resolve binary path at install time — avoids hardcoded ~/.bun/bin/ which may not exist
  _BCF_BIN=$(command -v better-ccflare 2>/dev/null || echo "$HOME/.local/bin/better-ccflare")
  mkdir -p "$HOME/.config/systemd/user"
  cat > "$HOME/.config/systemd/user/better-ccflare.service" << SERVICEEOF
[Unit]
Description=better-ccflare Claude load balancer proxy
After=default.target

[Service]
Type=simple
ExecStart=${_BCF_BIN} --serve --port ${CCFLARE_PORT}
Restart=on-failure
RestartSec=5
Environment="PORT=${CCFLARE_PORT}"
Environment="BETTER_CCFLARE_HOST=${CCFLARE_HOST}"
Environment="LB_STRATEGY=session"
Environment="LOG_LEVEL=INFO"
Environment="PATH=${HOME}/.local/bin:${HOME}/.bun/bin:/usr/local/bin:/usr/bin:/bin"
Environment="GOOGLE_APPLICATION_CREDENTIALS=${HOME}/.config/gcloud/application_default_credentials.json"

[Install]
WantedBy=default.target
SERVICEEOF

  systemctl --user daemon-reload 2>/dev/null || true
  systemctl --user enable better-ccflare 2>/dev/null || true
  systemctl --user start better-ccflare 2>/dev/null || true
  ok "better-ccflare service (http://${CCFLARE_HOST}:${CCFLARE_PORT})"
  echo "  Add accounts after install:"
  echo "    better-ccflare --add-account NAME --mode claude-oauth"
  echo "    better-ccflare --add-account NAME --mode kilo        (API key)"
  echo "    better-ccflare --add-account NAME --mode vertex-ai   (gcloud credentials)"
  echo "  ANTHROPIC_BASE_URL is auto-set in settings.json after accounts are added."

  # Billing header proxy (fixes better-ccflare issue #89):
  # - betterccflare binds to 127.0.0.1 only → Docker can't reach it directly
  # - OAuth accounts require x-anthropic-billing-header in system[0] for Sonnet/Opus
  # - This Bun proxy: 0.0.0.0:PROXY_PORT → injects header → 127.0.0.1:CCFLARE_PORT
  # - betterccflare upstream fix pending; when merged, this proxy still works (idempotent)
  _BUN_BIN=$(command -v bun 2>/dev/null || echo "$HOME/.local/bin/bun")
  if [[ -x "$_BUN_BIN" ]]; then
    mkdir -p "$HOME/.config/letta"
    cat > "$HOME/.config/letta/ccflare-billing-proxy.js" << 'BPROXY'
// ccflare-billing-proxy: fix for better-ccflare issue #89 (Sonnet/Opus 400 via OAuth)
// Injects x-anthropic-billing-header as system[0] block — required by Anthropic API
import { createHash } from "node:crypto";
const UPSTREAM = `http://127.0.0.1:${process.env.CCFLARE_PORT || 8080}`;
const PORT = Number(process.env.CCFLARE_PROXY_PORT || 8081);
const CC_VERSION = "2.1.77";
const SALT = "59cf53e54c78";
function computeBillingHeader(firstUserText) {
  const chars = [4, 7, 20].map(i => firstUserText[i] || "0").join("");
  const hash = createHash("sha256").update(SALT + chars + CC_VERSION).digest("hex").slice(0, 3);
  return `x-anthropic-billing-header: cc_version=${CC_VERSION}.${hash}; cc_entrypoint=cli; cch=00000;`;
}
function injectBillingHeader(body) {
  try {
    const json = JSON.parse(body);
    const sys = json.system;
    if (Array.isArray(sys) && sys.some(b => b.type === "text" && b.text?.startsWith("x-anthropic-billing-header:"))) return body;
    let firstUserText = "";
    if (Array.isArray(json.messages)) {
      for (const msg of json.messages) {
        if (msg.role === "user") {
          if (typeof msg.content === "string") firstUserText = msg.content;
          else if (Array.isArray(msg.content)) { const tb = msg.content.find(b => b.type === "text"); if (tb) firstUserText = tb.text || ""; }
          break;
        }
      }
    }
    const bb = { type: "text", text: computeBillingHeader(firstUserText) };
    if (Array.isArray(json.system)) json.system.unshift(bb);
    else if (typeof json.system === "string") json.system = [bb, { type: "text", text: json.system }];
    else json.system = [bb];
    return JSON.stringify(json);
  } catch { return body; }
}
Bun.serve({
  port: PORT, hostname: "0.0.0.0",
  async fetch(req) {
    const url = new URL(req.url);
    let body = await req.arrayBuffer();
    const headers = new Headers(req.headers);
    if (req.method === "POST" && url.pathname.includes("/v1/messages")) {
      const patched = injectBillingHeader(new TextDecoder().decode(body));
      body = new TextEncoder().encode(patched);
      headers.set("content-length", body.byteLength.toString());
    }
    const resp = await fetch(UPSTREAM + url.pathname + url.search, { method: req.method, headers, body: req.method !== "GET" && req.method !== "HEAD" ? body : undefined });
    return new Response(resp.body, { status: resp.status, headers: resp.headers });
  },
});
BPROXY

    cat > "$HOME/.config/systemd/user/ccflare-docker-proxy.service" << SVCEOF
[Unit]
Description=betterccflare billing header proxy (issue #89 — Sonnet/Opus via OAuth)
After=better-ccflare.service
BindsTo=better-ccflare.service

[Service]
Type=simple
ExecStart=${_BUN_BIN} run %h/.config/letta/ccflare-billing-proxy.js
Environment="CCFLARE_PORT=${CCFLARE_PORT}"
Environment="CCFLARE_PROXY_PORT=${CCFLARE_PROXY_PORT}"
Environment="PATH=${HOME}/.local/bin:${HOME}/.bun/bin:/usr/local/bin:/usr/bin:/bin"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=better-ccflare.service
SVCEOF
    systemctl --user daemon-reload 2>/dev/null || true
    systemctl --user enable ccflare-docker-proxy 2>/dev/null || true
    systemctl --user start ccflare-docker-proxy 2>/dev/null || true
    ok "ccflare-billing-proxy (0.0.0.0:${CCFLARE_PROXY_PORT} → 127.0.0.1:${CCFLARE_PORT}, billing header injection)"
  else
    warn "bun not found — ccflare-billing-proxy skipped (Letta LLM calls will fail)"
  fi
fi  # end $CCFLARE_SKIP

command -v kilocode &>/dev/null && ok "kilocode (exists)" || { run_q bun install -g @kilocode/cli && ok "kilocode" || warn "kilocode"; }
command -v vercel &>/dev/null && ok "vercel (exists)" || { run_q bun install -g vercel && ok "vercel" || warn "vercel"; }

